version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=next-saas
    networks:
      - dev_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - 3333:3333
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    command: sh -c "until pg_isready -h pg -p 5432; do echo waiting for database; sleep 2; done && cd /app/apps/api && pnpm prisma generate && pnpm run db:migrate && pnpm run dev"
    depends_on:
      - pg
    networks:
      - dev_network

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - 3000:3000
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
    depends_on:
      - api
    command: sh -c "cd /app/apps/web && pnpm run dev"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  pgdata: