version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "SEUUSUARIO"
      POSTGRES_PASSWORD: "SUASENHA"
      POSTGRES_DB: "pg"
    networks:
      - prod_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./prod.api.Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3333:3333
    depends_on:
      - pg
    networks:
      - prod_network
    volumes:
      - ./apps/api:/app/apps/api:ro
      - /app/apps/api/node_modules

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./prod.web.Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - prod_network
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/nginxcert.crt:/etc/nginx/ssl/nginxcert.crt
      - ./ssl/nginxkey.key:/etc/nginx/ssl/nginxkey.key  
    ports:
      - 80:80
      - 443:443
    networks:
      - prod_network
    depends_on:
      - web
      - api

networks:
  prod_network:
    driver: bridge

volumes:
  pgdata: