FROM node:alpine

WORKDIR /app

RUN npm install -g pnpm

# Configura banco
RUN apk add --no-cache postgresql-client

COPY ./*.json ./
COPY pnpm*.yaml .
RUN pnpm install

COPY . .

# Configura back
WORKDIR /app/apps/api
RUN pnpm install

# Configura front
WORKDIR /app/apps/web
RUN pnpm install